### ISSUE TITLE
Help: Issues with Plugin

### ISSUE THREAD

**Issue by siddhant-dev** [aparajita/capacitor-biometric-auth-demo#2]
Hi @aparajita 

 I have implemented your plugin but along with addResumeListenter and I'm getting error as App Plugin not implemented for android. 
 
 I'm using version 7.0.1 as my capacitor version is 5 and ionic v7 
 I'm using angular. Is there any configuration that I'm missing.

**Comment by aparajita** [comment]
I'm locking this because the issue belongs in the plugin repo, not in the demo repo.
